### ISSUE TITLE
Naviation option alignment issue on header.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#1]
Bug - Option not left aligned on header.
- Padding issue below button on naviation.

Exp - Add padding below buttons.
- Options should be left aligned.

Ref link - https://nimb.ws/8xBl4q

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - @ui-nitinrai Sir, Please add padding below buttons.
![image](https://user-images.githubusercontent.com/100753159/174748455-020d3e09-1bb7-4c79-a302-f2abaf5d52fc.png)

**Comment by ui-nitinrai** [comment]
@ankitcedcoss Share video please, there is padding below buttons you just need to scroll down

**Comment by ankitcedcoss** [comment]
@ui-nitinrai Please check viddeo - No padding added below buttons.
- https://drive.google.com/file/d/126Efq-wMoiifp48Ix7p0tlmXuy-hafTq/view

**Comment by ui-nitinrai** [comment]
Fixed .. please check again

**Comment by ankitcedcoss** [comment]
Bug Fixed
