### ISSUE TITLE
Validation Ui issue on account page on footer

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#13]
Bug - Validation error issue on footer and account pages.
Exp - Validation error should be visible in Red.
- Need to decrease spacing between validation error and field.
Ref Link - https://nimb.ws/WSB9tz
- https://nimb.ws/gsfDjd
- https://nimb.ws/GOqPb9

**Comment by ankitcedcoss** [comment]
Bug Fixed

**Comment by ui-nitinrai** [comment]
Not design issue, @devSharibAli render error messages below input field current they are outside of form input div

**Comment by ankitcedcoss** [comment]
Bug Fixed
