### ISSUE TITLE
Dropdown label issue on product page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#15]
Bug - Should not show size label on varient dropdown.
Exp - Sugg - Can change label to Select Varient or Aroma.
Ref Link - https://drive.google.com/file/d/1DhXfvtWDSMhD7bEdzmT2Rd8BZh3rp1kY/view

**Comment by ui-nitinrai** [comment]
Not a design issue, and I don't know how to fix it.

**Comment by ankitcedcoss** [comment]
Bug Fixed
