### ISSUE TITLE
discount popup inc/dec UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#17]
Bug - Inc/Dec button working on same when user click on it.
Exp - It should work seperatly on popup.
Ref Link - https://drive.google.com/file/d/1H40zmRpsbaVmD19l1naY1gfny4imbQD1/view

**Comment by devSharibAli** [comment]
Coming from app, can't modify  the script

**Comment by ankitcedcoss** [comment]
Closing on Not Required
