### ISSUE TITLE
Pagination UI issue on blogs section. - Tab and mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#18]
Bug - Pagination misplacing on tab UI.
- Pagination numbers not visible on mobile UI.

Exp - Pagination UI should be stable and pagination numbers should be visible on mobile and tab UI.

Ref Link - https://drive.google.com/file/d/1mYYbmlRYMpAfZhoN9iPdVYr6bXsGD9cO/view

**Comment by ui-nitinrai** [comment]
Not design issue, @devSharibAli please check ..same loop nesting issue cause pagination to render inside blog article card

**Comment by devSharibAli** [comment]
position fixed numbers not needed in mobile view

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - @devSharibAli Please check
- Pagination count not visible on mobile Ui.
- https://drive.google.com/file/d/1LrgfDmMwtXJobj3Q1g4NQ6IjuwCmsMzO/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
