### ISSUE TITLE
Spacing issue on blog tile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#19]
Bug - Showing spacing on blog tile UI.
Exp - Remove spacing from blog tile UI
Ref Link - https://drive.google.com/file/d/1m6oSsXmQ7dVHNWfKp8ne-FSq5TQKH3GI/view

**Comment by ui-nitinrai** [comment]
Not design Issue, @devSharibAli please check block article loop is broken. few article gets nested inside other article.

**Comment by ankitcedcoss** [comment]
@devSharibAli Please Look into this issue.

**Comment by ankitcedcoss** [comment]
https://drive.google.com/file/d/1am5GTWjtScKD2OydadK68nchjcEgdV_r/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
