### ISSUE TITLE
Wishlist icon UI issue on collection

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#5]
Bug - Showing bookmark icon instead of showing heart icon (wishlist icon) on product tile.
Exp - Sugg - Can replace icon with heart icon on wishlist icon on product tile.
Ref Link - https://nimb.ws/2HNTCQ

**Comment by ui-nitinrai** [comment]
Not an issue.

**Comment by ankitcedcoss** [comment]
Closing on Not Required
