### ISSUE TITLE
Image issue on homepage - mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/TRISTA-Store-Redesign-Speed#6]
Bug - Image not loading on homepage in mobile UI.
Exp - Image should be visible on homepage below "[What others are loving]" section.
Ref Link - https://drive.google.com/file/d/1ZAXHnrLzyJxRRPWQBpWiXoGf3FQDTC6V/view

**Comment by ui-nitinrai** [comment]
Not a design issue, and I don't know how to fix it.
